name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgres://postgres:postgres@localhost:65433/optrwork_test?sslmode=disable
      APP_URL: http://localhost:8080

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: optrwork_test
        ports: ['65433:5432']
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -race ./...

    - name: Lint
      run: make lint

    - name: Run web server
      run: make test-start-backend &

    - name: Tests
      run: make test-integration
